# Generated by Django 6.1 on 2026-08-22 19:42

import blog.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('type', models.CharField(choices=[('skyscraper', 'Skyscraper (120x600)'), ('leaderboard', 'Leaderboard (728x90)'), ('billboard', 'Billboard (970x250)'), ('mobile_banner', 'Mobile Banner (320x50)'), ('large_rectangle', 'Large Rectangle (336x280)'), ('half_page', 'Half Page (300x600)')], default='leaderboard', max_length=50)),
                ('image', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
                ('link', models.URLField(max_length=255, validators=[blog.validators.validate_http_url])),
                ('enddate', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Non Aktif')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('photo', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('photo', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
                ('caption', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
                ('created_by', models.CharField(blank=True, default='Anonymous', editable=False, max_length=150)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.URLField(max_length=255, validators=[blog.validators.validate_image_url])),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
